name: ultralytics_yolo_example
description: "Demonstrates how to use the ultralytics_yolo plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.1.2
  path_provider: ^2.0.0
  archive: ^4.0.7
  http: ^1.2.1
  go_router: ^16.0.0
  provider: ^6.1.1
  intl: ^0.18.1

  # ✅ 지도 관련 패키지 추가
  flutter_map: ^6.1.0 # 최신 안정 버전으로 확인 후 사용 권장
  latlong2: ^0.9.0 # 최신 안정 버전으로 확인 후 사용 권장

  ultralytics_yolo:
    path: ../

  cupertino_icons: ^1.0.8
  # ✅ 챗봇 및 환경 변수 관련 패키지 추가
  google_generative_ai: ^0.2.2 # Gemini API 사용을 위한 패키지 (최신 안정 버전 확인)
  flutter_dotenv: ^5.1.0 # .env 파일 사용을 위한 패키지 (최신 안정 버전 확인)

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/logo.png
    - assets/applogo.png
    - assets/models/dental_best_float32.tflite
    - .env # ✅ .env 파일을 assets에 추가하여 dotenv가 읽을 수 있도록 합니다.

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/applogo.png"
